### ISSUE TITLE
Upload large templates to s3 prior to deployment

### ISSUE THREAD

**Issue by jaymell** [daidokoro/qaz#14]
Hey there:

One of the templates I'm deploying is quite large, about 67k. AWS requires that templates over around 50k first be uploaded to an s3 bucket, so I'm currently unable to deploy the template via qaz. I think it may be necessary to have qaz potentially create a bucket prior to deployments.

Thanks.

**Comment by daidokoro** [comment]
Good spot Jay,

I've never run into this one myself as I tend to split big stacks in to multi smaller stacks for more control.

This is something I plan to implement in the next release, in a few days. 

You'll need to specify the bucket within the Stack config.

```yaml
stacks:
  vpc:
    bucket: mybucket
```

This is because it's possible to do cross-account deployments so one set of credentials for a stack may no have access to a bucket in another account. This is possible, however, i'll take some configuration outside of Qaz.

If the bucket exists, it'll simply write to it, if not it'll try to create it first.

This is something I plan to do this weekend. Let me know if the functionality will be something you're comfortable with.

For the time being it may be worth splinting your deployment and passing the Stack outputs/exports.

**Comment by daidokoro** [comment]
Hey Jay,

Just made a commit on the 0.50-beta branch to resolve this. You can test out the fix there if you want.

Version 0.50-beta has major change to the CLI relating to the  --template or -t flag. You will need to specify the stack name when using this flag. The is due to the source mechanism being enhanced.

For example:

```sh
# source can be a path, url, or s3 endpoint
$ qaz deploy -t vpc::source

# if you specify source within the config file, then you only need to specify the stack
$ qaz deploy vpc
```
I'm just trying to get some documentation via the Wiki and updates to Readme sorted before making this version live, as a few feature will be implemented and some breaking changes to the CLI.

Let me know if you run into any issues with the build. Thanks.

**Comment by daidokoro** [comment]
This has now been sorted! :-) #15

**Comment by jaymell** [comment]
Thanks. I really appreciate it!
